### ISSUE TITLE
Why panic instead of returning error in Call?

### ISSUE THREAD

**Issue by lazyhacker** [neelance/go#23]
I was wondering why Call panics instead of having an error return value?

```
func (v Value) Call(m string, args ...interface{}) Value {                      
    res, ok := v.call(m, makeArgs(args))                                        
    if !ok {                                                                    
         panic(Error{res})                                                       
    }                                                                           
    return res                                                                  
}   
```

**Comment by shurcooL** [comment]
If that were the case, the user would have to check the returned error value after each call to `Call`. Would that be better?

**Comment by lazyhacker** [comment]
Returning an error would allow the developer to take some action (e.g. show an error dialog) rather then have the module stopping.  Most consumers will not be looking at the console to see if there is an error and it'll just appear like nothing has happening.

**Comment by neelance** [comment]
You can still use `recover` to catch the panic.

I think returning an error everywhere would not be nice, because most JS functions will never throw an error. What we could consider is some separate function like `CallWithError` or something. If you think this would be worthwhile (please add a real-world example), then please open the issue on the main golang/go repository. I'll close it here for now since I'm phasing out this issue tracker.
