### ISSUE TITLE
JS interop layer

### ISSUE THREAD

**Issue by myitcv** [neelance/go#3]
Greetings @neelance - I'm interested in the JS interop layer (particularly given our discussions on the `js` package for GopherJS)

Where do things currently stand on that front? Anything I can do to help?

**Comment by neelance** [comment]
Hi Paul, sorry for the late reply. I've been busy with adding more core support before tackling the JS interop. But maybe we could start looking into that soon.

It will be more complicated than with GopherJS, since there is only a small keyhole between the WebAssembly world and the JS world and we'll need to squeeze everything through it. I think it would be good to start with making JS objects available to Go code, but skip everything async at first (event listeners, etc.). Then we can learn more about the problem space and look for a good solution for async.

We should talk on the Gophers slack. I can show you what the current state is and then we can discuss how to proceed.

**Comment by myitcv** [comment]
Sounds good, we can catch up in Slack.
