### ISSUE TITLE
Test failure in TestDependencies (syscall/js/callback)

### ISSUE THREAD

**Issue by johanbrandhorst** [neelance/go#8]
You might be aware, but I thought I'd open a tracking issue for others. The latest commit introduced a test failure:

```go
--- FAIL: TestDependencies (0.19s)
        deps_test.go:520: unexpected dependency: syscall/js/callback imports [os os/signal syscall syscall/js]
FAIL
FAIL    go/build        0.239s
```

**Comment by neelance** [comment]
@johanbrandhorst Thanks for opening the issue. I'm aware of the test failures, also the `time` package is broken with this commit. That's why it has `WIP` in its commit message. ;-) In the future, please do file broken tests, but only for non-WIP commits.

@shurcooL Initially `callback` depended on `os/signal`, so putting it into `syscall/js` caused a circular dependency. I've simplified the code now and removed the dependency to `os/signal`. Now callbacks are part of `syscall/js`.
